name: pyjs-wasm
channels:
  - conda-forge
dependencies:
  - cmake
  - pip
  - python=3.10
  - yarn
  - click
  - emsdk >=3.1.11
  - empack >=3.0.1
  - microsoft::playwright
  - ninja
  - nodejs >= 18.7.0
  - pyjs_code_runner >= 2.0.1