name: pyjs-wasm
channels:
  - https://repo.prefix.dev/emscripten-forge-4x
  - conda-forge
dependencies:
  - python=3.13
  - emscripten-abi >= 4.0
  - pybind11<3
  - pybind11_json
  - nlohmann_json
  - numpy
  - bzip2
  - sqlite
  - zlib
  - zstd
  - libffi
  - exceptiongroup
  - openssl
  - liblzma
  - xeus
  - xeus-lite
  - xeus-python
  - xeus-javascript
  - xtl
  - ipython
  - traitlets>=5.14.2