name: pyjs-dev
channels:
  - https://repo.prefix.dev/emscripten-forge-4x
  - conda-forge
dependencies:
  - python == 3.13
  - emscripten_emscripten-wasm32 >= 4.0
  - cmake
  - pip
  - yarn
  - click
  - microsoft::playwright <= 1.50
  - ninja
  - nodejs
  - pyjs_code_runner >= 2.0.1
  - exceptiongroup
  # documentation
  - jupytext
  - mkdocs
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-material
  - empack >=6.0.0
  - jupyter_server  # to enable contents
  - jupyterlite
  - jupyterlite-xeus >= 3.1.8
  - jupyterlite-sphinx
  - notebook >=7,<8  # to include the extension to switch between JupyterLab and Notebook
  # pyjs_code_runner dev deps
  - hatchling
  - pip:
    - JLDracula
    - pyjs_code_runner >= 3.0
